#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

//* 1. Initialize aplication
$app = new Application('Laracasts Demo', '1.0'); //* Changes the default 'Console Tool'

//* 2. Add commands
$app->add(new Acme\RenderCommand);

//* Run application
$app->run();
